site_name: LeetCode Solutions
nav:
  - Home: index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
      primary: white


markdown_extensions:
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sureshchandras3kar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suresh-chandrasekar/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ChennaiProgramr

copyright: 
      "&copy; 2024 <a href='https://github.com/sureshchandras3kar'>suresh chandra sekar</a>. All rights reserved."
