site_name: LeetCode Solutions
site_url: https://sureshchandras3kar.github.io/leetcode_solutions/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
      primary: white

markdown_extensions:
  - admonition
  - pymdownx.extra
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
        base_path: 'src/'
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Problems:
    - Palindrome numbers: problems/palindrome_number.md


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sureshchandras3kar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/suresh-chandrasekar/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ChennaiProgramr

copyright: 
      "&copy; 2024 <a href='https://github.com/sureshchandras3kar'>suresh chandra sekar</a>. All rights reserved."
